const functionKeys = [
  { code: "F1", keyCode: 112 },
  { code: "F2", keyCode: 113 },
  { code: "F3", keyCode: 114 },
  { code: "F4", keyCode: 115 },
  { code: "F5", keyCode: 116 },
  { code: "F6", keyCode: 117 },
  { code: "F7", keyCode: 118 },
  { code: "F8", keyCode: 119 },
  { code: "F9", keyCode: 120 },
  { code: "F10", keyCode: 121 },
  { code: "F11", keyCode: 122 },
  { code: "F12", keyCode: 123 },
]

const digitKeys = [
  { code: "Digit0", keyCode: 48 },
  { code: "Digit1", keyCode: 49 },
  { code: "Digit2", keyCode: 50 },
  { code: "Digit3", keyCode: 51 },
  { code: "Digit4", keyCode: 52 },
  { code: "Digit5", keyCode: 53 },
  { code: "Digit6", keyCode: 54 },
  { code: "Digit7", keyCode: 55 },
  { code: "Digit8", keyCode: 56 },
  { code: "Digit9", keyCode: 57 },
]

const alphabetKeys = [
  { code: "KeyA", keyCode: 65 },
  { code: "KeyB", keyCode: 66 },
  { code: "KeyC", keyCode: 67 },
  { code: "KeyD", keyCode: 68 },
  { code: "KeyE", keyCode: 69 },
  { code: "KeyF", keyCode: 70 },
  { code: "KeyG", keyCode: 71 },
  { code: "KeyH", keyCode: 72 },
  { code: "KeyI", keyCode: 73 },
  { code: "KeyJ", keyCode: 74 },
  { code: "KeyK", keyCode: 75 },
  { code: "KeyL", keyCode: 76 },
  { code: "KeyM", keyCode: 77 },
  { code: "KeyN", keyCode: 78 },
  { code: "KeyO", keyCode: 79 },
  { code: "KeyP", keyCode: 80 },
  { code: "KeyQ", keyCode: 81 },
  { code: "KeyR", keyCode: 82 },
  { code: "KeyS", keyCode: 83 },
  { code: "KeyT", keyCode: 84 },
  { code: "KeyU", keyCode: 85 },
  { code: "KeyV", keyCode: 86 },
  { code: "KeyW", keyCode: 87 },
  { code: "KeyX", keyCode: 88 },
  { code: "KeyY", keyCode: 89 },
  { code: "KeyZ", keyCode: 90 },
]

const numpadKeys = [
  { code: "Numpad0", keyCode: 96 },
  { code: "Numpad1", keyCode: 97 },
  { code: "Numpad2", keyCode: 98 },
  { code: "Numpad3", keyCode: 99 },
  { code: "Numpad4", keyCode: 100 },
  { code: "Numpad5", keyCode: 101 },
  { code: "Numpad6", keyCode: 102 },
  { code: "Numpad7", keyCode: 103 },
  { code: "Numpad8", keyCode: 104 },
  { code: "Numpad9", keyCode: 105 },
  { code: "NumpadMultiply", keyCode: 106 },
  { code: "NumpadAdd", keyCode: 107 },
  { code: "NumpadSubtract", keyCode: 109 },
  { code: "NumpadDecimal", keyCode: 110 },
  { code: "NumpadDivide", keyCode: 111 },
  { code: "NumpadEnter", keyCode: 13 },
]

const arrowKeys = [
  { code: "ArrowLeft", keyCode:37  },
  { code: "ArrowUp", keyCode: 38 },
  { code: "ArrowRight", keyCode: 39 },
  { code: "ArrowDown", keyCode: 40 },
]

const otherKeys = [
  { code: "Backspace", keyCode: 8 },
  { code: "Tab", keyCode: 9 },
  { code: "Enter", keyCode: 13 },
  { code: "ShiftLeft", keyCode: 16 },
  { code: "ShiftRight", keyCode: 16 },
  { code: "ControlLeft", keyCode: 17 },
  { code: "ControlRight", keyCode: 17 },
  { code: "AltLeft", keyCode: 18 },
  { code: "AltRight", keyCode: 18 },
  { code: "CapsLock", keyCode: 20 },
  { code: "Escape", keyCode: 27 },
  { code: "Space", keyCode: 32 },
  { code: "PageUp", keyCode: 33 },
  { code: "PageDown", keyCode: 34 },
  { code: "End", keyCode: 35 },
  { code: "Home", keyCode: 36 },
  { code: "Insert", keyCode: 45 },
  { code: "Delete", keyCode: 46 },
  { code: "MetaLeft", keyCode: 91 },
  { code: "NumLock", keyCode: 144 },
  { code: "Semicolon", keyCode: 186 },
  { code: "Equal", keyCode: 187 },
  { code: "Comma", keyCode: 188 },
  { code: "Minus", keyCode: 189 },
  { code: "Period", keyCode: 190 },
  { code: "Slash", keyCode: 191 },
  { code: "Backquote", keyCode: 192 },
  { code: "BracketLeft", keyCode: 219 },
  { code: "Backslash", keyCode: 220 },
  { code: "BracketRight", keyCode: 221 },
  { code: "Quote", keyCode: 222 },
]

const keys = [
  ...functionKeys,
  ...digitKeys,
  ...alphabetKeys,
  ...numpadKeys,
  ...arrowKeys,
  ...otherKeys
]

export default keys